const express = require('express');
require('dotenv').config();
const OpenAI = require('openai');
const fs = require('fs'); 
const path = require('path');
const { exec } = require('child_process'); // Add this line

const app = express();
const port = 3000;

app.use(express.json());

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY
});

async function generateFiles(names) {
  await generateTextAndAudio(names);
  await scrapeImages(names);
}

async function generateTextAndAudio(nameArr) {
  // Loop through the name array to generate text for each name
  for (const name of nameArr) {
    try {
      // Read the content of the text file
      let fileName = name.replace(/\s/g, '');
      const fileContent = fs.readFileSync(path.join(__dirname, `../scraped_articles/${fileName}.txt`), "utf-8");

      // Prepare the prompt
      const prompt = `Use the following text to create a script for a youtube essay: \n\n${fileContent}`;

      // Call the OpenAI API
      const response = await openai.chat.completions.create({
        model: "gpt-4o-mini",
        messages: [
          { role: "developer", content: "You are a creative writer and youtuber. You will be presenting a video essay based on a txt file. Please respond solely with what you will say as the narrator of the script, with no scene directions. It is vital to keep your response to under 4000 characters." },
          { role: "user", content: prompt}
        ]
      });

      // Extract and log the generated text
      const generatedText = response.choices[0]?.message?.content;
      if (!generatedText) {
        throw new Error('No text generated by OpenAI API');
      }

      await textToSpeech(generatedText, fileName);
      // Save the generated text to a file
      fs.writeFileSync(path.join(__dirname, `../content/generated_text/${fileName}.txt`), generatedText);
    } catch (error) {
      console.error("Error:", error);
    }
  }
}

async function textToSpeech(text, fileName) {
  console.log('start text to speech', fileName);
  const speechFile = path.resolve(__dirname, `../content/generated_audio/baseball/${fileName}.mp3`);
  const mp3 = await openai.audio.speech.create({
    model: "tts-1",
    voice: "alloy",
    input: text,
  });
  const buffer = Buffer.from(await mp3.arrayBuffer());
  await fs.promises.writeFile(speechFile, buffer);
  console.log('Audio file saved:', speechFile);
}

async function scrapeImages(args = []) {
  // Access scrape_images.py in the scripts folder and pass in the names array
  const quotedArgs = args.map(name => `"${name}"`).join(' ');

  exec(`python3 ${path.join(__dirname, '../scripts/scrape_images.py')} ${quotedArgs}`, (error, stdout, stderr) => {
    if (error) {
      console.error(`Error: ${error.message}`);
      return;
    }
    if (stderr) {
      console.error(`stderr: ${stderr}`);
      return;
    }
    console.log(`stdout: ${stdout}`);
  });
}

app.post('/generate-files', async (req, res) => {
  let { nameArr } = req.body;

  try {
    await generateFiles(nameArr);
    res.status(200).send('Text and audio generated successfully');
  } catch (error) {
    res.status(500).send(`Error generating text and audio: ${error}`);
  }
});

app.post('/generate-images', async (req, res) => {
  let { nameArr } = req.body;

  try {
    await scrapeImages(nameArr);
    res.status(200).send('Images generated successfully');
  } catch (error) {
    res.status(500).send(`Error generating images: ${error}`);
  }
});

app.listen(port, () => {
    console.log(`Server is running on http://localhost:${port}`);
});